### ISSUE TITLE
Picking No when prompted to call method after deployment results in error

### ISSUE THREAD

**Issue by Swader** [OpenZeppelin/openzeppelin-contracts-ethereum-package#58]
When using the StandaloneERC20 as per the [guide](https://docs.openzeppelin.com/sdk/2.5/linking) if you pick "No" when asked to call a function after deployment, an error is produced.

```bash
? Pick a contract to instantiate @openzeppelin/contracts-ethereum-package/StandaloneERC20
? Pick a network development
√ Deploying @openzeppelin/contracts-ethereum-package dependency to network dev-1564745320775
All contracts are up to date
? Do you want to call a function on the instance after creating it? No
Possible initialization method (initialize) found in contract. Make sure you initialize your instance.
Invalid JSON RPC response: ""
```

Reproduce by following above flow.

Recommended fix: remove Yes/No option from contracts that can't be deployed without those an init function being called.

**💻 Environment**

- Windows 10 + Cmder
- contracts-ethereum-package@2.2.1
- openzeppelin-cli 2.5.1

**Comment by frangio** [comment]
Thanks for reporting @Swader. This sounds more like a problem in `openzeppelin-cli`. Would you mind reporting this at [forum.openzeppelin.com](https://forum.openzeppelin.com)?

**Comment by Swader** [comment]
Sure thing
