### ISSUE TITLE
Change msg.sender and msg.data in all contracts

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts-ethereum-package#61]
Have all contracts inherit from a base context that defines msgSender and msgData with their default implementations, so they can be overridden by the GSN context.

Port this change to oz/contracts as well.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/commit/89835152ce5b7b241a95ef00e0a62dc9a8e3fb62.
