### ISSUE TITLE
Invalid number of parameters for "balanceOf". Got 1 expected 7!

### ISSUE THREAD

**Issue by TamirTian** [OpenZeppelin/openzeppelin-contracts-ethereum-package#71]
**💻 Environment**
@openzeppelin/upgrades@2.5.3
@openzeppelin/contracts-ethereum-package@2.3.0
solc 0.5.2

**📝 Details**
I want to call the contract by **balanceOf** method, but i got below error
```js
 Error: Invalid number of parameters for "balanceOf". Got 1 expected 7!
```
I printed the **balanceOf** ABI. It's magical, i guess they are conflicts
```
console.log(proxy._jsonInterface.find(item => item.name === 'balanceOf'))
```

![image](https://user-images.githubusercontent.com/20901836/67358624-a04e6280-f593-11e9-85c7-03d4ff111a7e.png)
![image](https://user-images.githubusercontent.com/20901836/67358631-a5131680-f593-11e9-8bf9-551453396b87.png)

**🔢 Code to reproduce bug**

**Comment by abcoathup** [comment]
Hi @TamirTian,

This appears to be the same issue as https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/issues/70 with truffle corrupting the abi field on the JSON artifacts when the package was built.

As a workaround, reverting to 2.2.3 resolves the issue:
```
npm uninstall @openzeppelin/contracts-ethereum-package
oz link @openzeppelin/contracts-ethereum-package@2.2.3
```

**Comment by nventuro** [comment]
Indeed, this is the same as #70. Closing as duplicate.
