### ISSUE TITLE
Deploy the contracts to Ethereum Classic and the Ethereum Classic Kotti Testnet

### ISSUE THREAD

**Issue by husainfazel** [OpenZeppelin/openzeppelin-contracts-ethereum-package#72]
**🧐 Motivation**
Many developers choose Ethereum Classic to deploy their contracts to. By January, ETC's upcoming Agartha hard fork will provide feature-parity with Constantinople. It would be useful to developers on ETC if the `openzeppelin-contracts-ethereum-package` contracts could be deployed to Ethereum Classic's mainnet and the primary testnet Kotti (https://github.com/goerli/testnet).

**📝 Details**
I have tried to deploy this myself manually. I have an ETC account with a balance on it and I have the following settings in my network.js file:

```
require('dotenv').config();
const HDWalletProvider = require('truffle-hdwallet-provider');
module.exports = {
  compilers: {
    solc: {
      version: '0.5.1',
      settings: {
        evmVersion: 'byzantium'
      }
    }
  },
  networks: {
    kotti: {
      provider: () => new HDWalletProvider(
        [process.env.DEV_PRIVATE_KEY], 
        "https://www.ethercluster.com/kotti"),
      networkId: '6'
    }
  }
};
``` 

Here is the output I get from open-zeppelin-sdk:
```
$ openzeppelin push                                                
Nothing to compile, all contracts are up to date.
? Pick a network kotti
? One or more linked dependencies are not yet deployed on dev-6.
Do you want to deploy them now? Yes
✖ Deploying @openzeppelin/contracts-ethereum-package dependency to network dev-6
Failed deployment of dependency @openzeppelin/contracts-ethereum-package with error: Failed to check for transaction receipt:
{}
```

**Comment by abcoathup** [comment]
Hi @husainfazel,

I suggest this issue can be closed now.

I answered this in the forum, the issue was the EVM version of the Proxy and ProxyAdmin contracts in OpenZeppelin CLI.  A Byzantium version of the OpenZeppelin CLI was created to allow contract creation on Kotti.
https://forum.openzeppelin.com/t/deploying-a-token-that-uses-contracts-ethereum-package-to-ethereum-classic/1810/4
