### ISSUE TITLE
cannot use erc721 correctly from this package

### ISSUE THREAD

**Issue by wuichen** [OpenZeppelin/openzeppelin-contracts-ethereum-package#77]
trying to use erc721full from this package but cannot initialize it correctly. the compiler is telling me that the constructor shouldnt have any arguments. error gets thrown at here. everything works when i switch the library to the original onezeppelin/contracts library

**💻 Environment**

im using zepkit from the site. 

**🔢 Code to reproduce bug**
 
`import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/IERC721Enumerable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721Enumerable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/IERC721Metadata.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721Metadata.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721Full.sol"
contract Thing is ERC721Full, ERC721MetadataMintable, ERC721Burnable, Ownable {
    using SafeMath for uint256;
    struct Price {
        uint256 tokenId;
        uint256 price;
        string metaId;
        TokenState state;
    }

    mapping(uint256 => Price) public items;
    constructor(
        string memory name,
        string memory symbol,
        string memory uri,
        address payable fee,
        address payable creator
    ) public ERC721Full(name, symbol) {
        maker = creator;
        feeAddress = fee;
        baseUri = uri;
        id = 0;
        transferOwnership(creator);
        _addMinter(creator);

    }}`

**Comment by wuichen** [comment]
<img width="711" alt="Screen Shot 2020-03-24 at 2 43 27 AM" src="https://user-images.githubusercontent.com/6353587/77351807-425bbc00-6d79-11ea-9f57-4ce4ed008d85.png">

**Comment by abcoathup** [comment]
Hi @wuichen!  

Thanks for your question. I have posted it in the Community Forum, where it can get a faster response by the community and the team. I will close this issue so we can continue the discussion there!

https://forum.openzeppelin.com/t/how-to-create-an-upgradeable-erc721/2513
