### ISSUE TITLE
Add solc 0.6.+ support

### ISSUE THREAD

**Issue by orenyodfat** [OpenZeppelin/openzeppelin-contracts-ethereum-package#79]
**🧐 Motivation**

we are using @openzeppelin/upgrades and @openzeppelin/contracts-ethereum-package in our project .
We implemented a DAOFactory contract which is based(and use) on @openzeppelin/upgrades.
We would like to be able to compile this contract + all other contracts with solc 0.6 ..
We can come out with a workaround which works with the precompiled contracts you provide (can you give a reference to a truffle project which doing so? ) though I guess that it will complicated our truffle project..I would like to avoid it.

see https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1463

**Comment by orenyodfat** [comment]
@nventuro ?

**Comment by frangio** [comment]
Support for solc 0.6 will be included in OpenZeppelin Contracts 3.0. Once that is released (it's still in release candidate period) we will release a version of this package.

Keep in mind that the it will probably not be possible to upgrade existing contracts across this major version, because there will be backwards-incompatible changes to storage layout.

**Comment by orenyodfat** [comment]
> Support for solc 0.6 will be included in OpenZeppelin Contracts 3.0. Once that is released (it's still in release candidate period) we will release a version of this package.

https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v3.0.0

**Comment by abcoathup** [comment]
Hi @orenyodfat,

An upgradeable version of OpenZeppelin Contracts 3.0 will be about four weeks away, I will let you know when we have a release. 

Please note: storage layout changes likely means that contracts can't be upgraded from 2.5 to 3.0.

**Comment by abcoathup** [comment]
Hi @orenyodfat,
OpenZeppelin Contracts Ethereum Package v3.0 has been released:
https://forum.openzeppelin.com/t/openzeppelin-contracts-ethereum-package-v3-0/2852

**Comment by orenyodfat** [comment]
Thanks.
See https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/issues/86
