### ISSUE TITLE
Broken Non-Interactive Deployments, Faulty Docs

### ISSUE THREAD

**Issue by hickscorp** [OpenZeppelin/openzeppelin-contracts-ethereum-package#80]
## Abstract

We are trying to update from a previous version of OZ to the latest.

We had automation scripts in charge of deploying things on dev / staging environments before and they broke.

The commands we were issuing before were something like:

```
yarn oz create Access --skip-compile --init initialize $zosArgs --args "$GOVERNOR"
```

We saw the notice during deployment that `create` was deprecated, so we used `deploy` instead. However, we're stuck for several reasons.

## The `--kind` Argument

The documentation for the new required `--kind` argument shows:
![image](https://user-images.githubusercontent.com/822933/78247125-393dbe00-74e2-11ea-9625-ebea181d35e9.png)
By trial and error, we found out that `--kind upgradeable` would probably be the equivalent of what we had before (our contracts inherit from `@openzeppelin/upgrades/contracts/Initializable.sol`).
Is that correct? I would hint that it's not.
Reading the documentation tells us that the inheritance from `Initializable.sol` doesn't seem to be required anymore - but in that case, how would we migrate contracts that inherit from `Initializable.sol` in production?

## The `--init` Argument

As we're trying to get the new `oz deploy` command to run with the `--no-interactive` flag, we're also trying to understand how to have the old equivalent of `--init` to work. From what I understand, there's no such thing - what's the right way of doing things here?

**Comment by frangio** [comment]
Hi @hickscorp. Thank you for reporting. I'm sorry you ran into these issues.

I've fixed the documentation issue for `deploy --kind`.

I'm not sure where you read that `Initializable` is no longer required. This is wrong, it's still required. There should be no changes to the contract source code. (Perhaps you're looking at the plans for 3.0?)

`oz deploy --kind upgradeable` works similar to `oz create` but the arguments are a bit different. It is assumed that the initializer is called `initialize`, and it's not possible to customize it with `--init` any more.

As for the arguments that will be passed to `initialize`, they are specified in the command line as separate arguments to `oz deploy` (so no longer joined by commas).

Assuming that there is a single argument to the `Access` initializer, to replicate your command:

```
yarn oz create Access --skip-compile --init initialize $zosArgs --args "$GOVERNOR"
```

you should now run:


```
yarn oz deploy Access "$GOVERNOR" --skip-compile $zosArgs
```

It's the same, with `--init initialize` removed, and I reordered the commands just to make it clear that `"$GOVERNOR"` is a positional argument and not a flag.

**Comment by hickscorp** [comment]
Thanks for the reply and quick action taken on fixing the docs, @frangio . I'm closing this issue for now - if I encounter other issues with the docs I'll re-open.
