### ISSUE TITLE
Difference between openzeppelin-contracts npm package

### ISSUE THREAD

**Issue by codaelux** [OpenZeppelin/openzeppelin-contracts-ethereum-package#84]
[https://github.com/OpenZeppelin/openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) runs on compiler 6.0+ current npm [version 2.5.0 ](https://www.npmjs.com/package/@openzeppelin/contracts-ethereum-package/v/2.5.0) of this repo runs with compiler 5.0

**Comment by abcoathup** [comment]
Hi @codaelux!  Thanks for your question. I have posted it in the Community Forum, where it can get a faster response by the community and the team. I will close this issue so we can continue the discussion there!

Discussion:
https://forum.openzeppelin.com/t/difference-between-openzeppelin-contracts-and-openzeppelin-contracts-ethereum-package/2815

See Issue: https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/issues/79 for Solidity 0.6 support
