### ISSUE TITLE
StandaloneERC20 was removed in 3.0 ? 

### ISSUE THREAD

**Issue by orenyodfat** [OpenZeppelin/openzeppelin-contracts-ethereum-package#91]
MintableERC20 and the onlyMinter modifier ?

**Comment by frangio** [comment]
The alternative to the standalone contracts is the new [preset contracts](https://docs.openzeppelin.com/contracts/3.x/api/presets).

Please refer to [this thread on the forum](https://forum.openzeppelin.com/t/where-is-erc20mintable-sol-in-openzeppelin-contracts-3-0/2283/3?u=frangio).

>For this release, we are removing the current role contracts, which includes `MinterRole`. Since we are removing this role, we are also removing the `ERC20Mintable` contract which used it.

>V3 doesn't include `ERC20Mintable` because the core contracts were made less opinionated: you get the internal `_mint` function in `ERC20` and you can expose it as an external function however you want. This grew out of a feeling that basic contracts like v2's `ERC20Mintable` can be inadequate when a project grows, and it's also related to the fact that we introduced the more feature-complete `AccessControl` but we didn't want to force everyone to use it. To balance this out, we introduced the "preset" contracts that piece together the different components in an opinionated way to provide ready to use contracts. So I'm glad to hear that worked for you.
