### ISSUE TITLE
The `GSNRecipient` file name differs from the contract name

### ISSUE THREAD

**Issue by ilyakmet** [OpenZeppelin/openzeppelin-contracts-ethereum-package#92]
**💻 Environment**

OpenZeppelin Contracts Ethereum Package v3.0.0

**📝 Details**

[GSNRecipient.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/blob/master/contracts/GSN/.sol)  has different abstract contract name `GSNRecipientUpgradeSafe`. This causes an error, when you try to use `npx oz deploy`.

**🔢 Code to reproduce bug**

# GSNRecipientUpgradeSafe.sol

```js
abstract contract GSNRecipientUpgradeSafe is Initializable, IRelayRecipient, ContextUpgradeSafe {
    function __GSNRecipient_init() internal initializer {
        __Context_init_unchained();
        __GSNRecipient_init_unchained();
    }
...
}
```
# Counter.sol

See [Sending Gasless Transactions](https://docs.openzeppelin.com/learn/sending-gasless-transactions)

```js
// contracts/Counter.sol
pragma solidity ^0.5.0;

import "@openzeppelin/contracts-ethereum-package/contracts/GSN/GSNRecipient.sol";

contract Counter is GSNRecipient {...}
```

# Compiler errors

```bash
Compilation errors: 
contracts/Counter.sol:5:21: DeclarationError: Identifier not found or not unique.
contract Counter is GSNRecipient {
```

**Comment by frangio** [comment]
Thanks for reporting. This is by design now, but it should not cause any issues. In your code you should use the contract name with the `UpgradeSafe` suffix, even if the file name does not contain the suffix. Please try that out and let me know if it works.
